[build]
    base = "myendpointsproject/"
    command = "echo 'default context'"

[[edge_functions]]
    path = "/hello"
    function = "hello"

[[edge_functions]]
    path = "/"
    function = "accounts"